# Create a new debt record
POST http://localhost:3001/debt-sup
Content-Type: application/json

{
    "supplier_id": 5,
    "debt_sup_amount": 100,
    "debt_sup_timestamp": "2023-12-11T10:00:00.000Z"
}
###

# Subtract an amount from a supplier's debt
PATCH http://localhost:3001/debt-sup/1
Content-Type: application/json

{
    "amount": 49.75
}

###

# Get all debt records
GET http://localhost:3001/debt-sup

###

# Get a debt by Supplier
GET http://localhost:3001/debt-sup/4

###

# Update a debt record
PUT http://localhost:3001/debt-sup/4/2024-12-11T09:00:00.000Z
Content-Type: application/json

{
    "debt_cus_amount": 200
}

###

# Delete a debt record
DELETE http://localhost:3001/debt-sup/5/2023-12-11T10:00:00.000Z