### Get all debts
GET http://localhost:3000/debt-cus

### Get a specific debt by ID
GET http://localhost:3000/debt-cus/1

### Create a new debt record
POST http://localhost:3000/debt-cus
Content-Type: application/json

{
  "customer_id": 1,
  "debt_cus_amount": 7500,
  "debt_cus_timestamp":20
}


### Update a specific debt by ID and time
PUT http://localhost:3000/debt-cus/1/2024-12-12T12:00:00Z
Content-Type: application/json

{
  "supplier_id": 2,
  "debt_sup_amount": 8000
}

### Delete a specific debt by ID
DELETE http://localhost:3000/debt-cus/1
