### Get all invoices
GET http://localhost:3000/invoices
Content-Type: application/json

###

### Get an invoice by ID
GET http://localhost:3000/invoices/5
Content-Type: application/json

###

### Create a new invoice
POST http://localhost:3000/invoices
Content-Type: application/json

{
  "invoice_cus_total_amount": 500,
  "customer_id": 1,
  "invoice_lines": [
    {
      "product_id": 1,
      "product_variant_id": 1,
      "invoice_cus_line_quantity": 3,
      "invoice_cus_line_price": 100
    },
    {
      "product_id": 2,
      "product_variant_id": null,
      "invoice_cus_line_quantity": 1,
      "invoice_cus_line_price": 200
    }
  ]
}

###

### Update an existing invoice
PUT http://localhost:3000/invoices/1
Content-Type: application/json

{
  "invoice_cus_total_amount": 600,
  "customer_id": 2
}

###

### Delete an invoice
DELETE http://localhost:3000/invoices/6
Content-Type: application/json