# Test Get All Invoice Supplies
GET http://localhost:3000/customers
Accept: application/json

###

# Test Get Invoice Supply by ID
GET http://localhost:3000/invoice-lines
Accept: application/json

###

# Test Create Invoice Supply
GET http://localhost:3000/invoices
Content-Type: application/json

{
  "supplier_id": 1,
  "product_id": 2,
  "quantity": 10,
  "unitPrice": 100.50
}

###

# Test Update Invoice Supply by ID
GET http://localhost:3000/invoice-sup-lines
Content-Type: application/json

{
  "supplier_id": 1,
  "product_id": 3,
  "quantity": 15,
  "unitPrice": 120.75
}

###

# Test Delete Invoice Supply by ID
DELETE http://localhost:3000/api/invoiceSupp/1


###

# Test Update Invoice Supply by ID
GET http://localhost:3000/invoices-sup
Content-Type: application/json

{
  "supplier_id": 1,
  "product_id": 3,
  "quantity": 15,
  "unitPrice": 120.75
}

###

###

# Test Update Invoice Supply by ID
GET http://localhost:3000/debt-sup/2
Content-Type: application/json

{
  "supplier_id": 1,
  "product_id": 3,
  "quantity": 15,
  "unitPrice": 120.75
}

###
