# Get all product variants
GET http://localhost:3001/product-variants
Content-Type: application/json

###

# Get a product variant by ID
GET http://localhost:3001/product-variants/6
Content-Type: application/json

###

# Create a new product variant
POST http://localhost:3001/product-variants
Content-Type: application/json

{
    "product_id": 28,
    "variant_barcode": "1235465",
    "variant_price": 300,
    "variant_quantity": 4,
    "variant_stock_level": 2
}

###

# Update an existing product variant
PUT http://localhost:3001/product-variants/1
Content-Type: application/json

{
    "variant_price": 180.00,
    "variant_stock_level": 90
}

###

# Delete a product variant
DELETE http://localhost:3001/product-variants/1
Content-Type: application/json
