# Test Get All Debts
GET http://localhost:3000/api/debts
Accept: application/json

###

# Test Get Debt by ID
GET http://localhost:3000/api/debts/1
Accept: application/json

###

# Test Create Debt
POST http://localhost:3000/api/debts
Content-Type: application/json

{
  "supplier_id": 1,
  "paidAmount": 2000,
  "PaymentDate": 20231210,
  "RemainingAmount": 1500
}

###

# Test Update Debt by ID
PUT http://localhost:3000/api/debts/1
Content-Type: application/json

{
  "supplier_id": 1,
  "paidAmount": 2500,
  "PaymentDate": 20231212,
  "RemainingAmount": 1200
}

###

# Test Delete Debt by ID
DELETE http://localhost:3000/api/debts/1
